### ISSUE TITLE
How to access nuxt service through address

### ISSUE THREAD

**Issue by wodepig** [NicolaSpadari/nuxtor#1]
![image](https://github.com/user-attachments/assets/d4be2cd5-9f24-4c7b-86b0-ca8123979ce8)
When I start the application, there is no way to access the service provided by nuxt through the url address.
![image](https://github.com/user-attachments/assets/9a89c009-411e-420d-a592-0b3f3bd928d5)
I want to access the background service through http:// localhost:3001/api/hello

**Comment by NicolaSpadari** [comment]
Nuxt SSR is disabled, as the backend is handled by Tauri.
There is a more exhaustive explatantion of why here: https://medium.com/@kinxyo/nuxt-3-integration-in-tauri-5dd07ede3c98
But the short explanation is: Tauri doesn’t support server based solutions
