### ISSUE TITLE
How can I see the logs?

### ISSUE THREAD

**Issue by ok-oldking** [NicolaSpadari/nuxtor#2]
I'm new to tauri and nuxt.
I can't get the log working either by console.log or using the "@tauri-apps/plugin-log"

```
import { trace, info, error, attachConsole } from "@tauri-apps/plugin-log";
info(`currentPlatform {currentPlatform}`);
info!("Razor located: 1111");
console.log('22222222222');
```

**Comment by NicolaSpadari** [comment]
Hello, you shouldn't need the plugin for logging info, as you can see I just added a random console log and I see it correctly
![Screenshot 2024-09-02 at 09 23 55](https://github.com/user-attachments/assets/0c06c4a1-4cb3-4971-a2cb-4d08f24cda72)

Please keep in mind that logging is available during development and in debug build, not in the compiled final application

**Comment by ok-oldking** [comment]
Thank you for the reply, I didn't know about the developer console, I was looking in the termimal
